# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "45c505bc008ff0e87788ecc6611bc9db"
name = "Blog-ai-agent"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_product_feeds,write_product_feeds,read_products,read_content,write_content"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
